update master_settings set additional_info = '{"country_code": "+62", "country_iso": "ID"}'::jsonb where setting_name = 'INDONESIA';
update master_settings set additional_info = '{"country_code": "+60", "country_iso": "MY"}'::jsonb where setting_name = 'MALAYSIA';
update master_settings set additional_info = '{"country_code": "+65", "country_iso": "SG"}'::jsonb where setting_name = 'SINGAPORE';
update master_settings set additional_info = '{"country_code": "+673", "country_iso": "BN"}'::jsonb where setting_name = 'BRUNEI DARUSSALAM';
update master_settings set additional_info = '{"country_code": "+1", "country_iso": "US"}'::jsonb where setting_name = 'UNITED STATES';
update master_settings set additional_info = '{"country_code": "+61", "country_iso": "AU"}'::jsonb where setting_name = 'AUSTRALIA';
update master_settings set additional_info = '{"country_code": "+84", "country_iso": "VN"}'::jsonb where setting_name = 'VIETNAM';
update master_settings set additional_info = '{"country_code": "+965", "country_iso": "KW"}'::jsonb where setting_name = 'KUWAIT';
update master_settings set additional_info = '{"country_code": "+81", "country_iso": "JP"}'::jsonb where setting_name = 'JAPAN';
update master_settings set additional_info = '{"country_code": "+380", "country_iso": "UA"}'::jsonb where setting_name = 'UKRAINE';
update master_settings set additional_info = '{"country_code": "+1", "country_iso": "CA"}'::jsonb where setting_name = 'CANADA';
update master_settings set additional_info = '{"country_code": "+63", "country_iso": "PH"}'::jsonb where setting_name = 'PHILIPPINES';
update master_settings set additional_info = '{"country_code": "+852", "country_iso": "HK"}'::jsonb where setting_name = 'HONG KONG';
update master_settings set additional_info = '{"country_code": "+966", "country_iso": "SA"}'::jsonb where setting_name = 'SAUDI ARABIA';
update master_settings set additional_info = '{"country_code": "+64", "country_iso": "NZ"}'::jsonb where setting_name = 'NEW ZEALAND';
update master_settings set additional_info = '{"country_code": "+66", "country_iso": "TH"}'::jsonb where setting_name = 'THAILAND';
update master_settings set additional_info = '{"country_code": "+33", "country_iso": "FR"}'::jsonb where setting_name = 'FRANCE';
update master_settings set additional_info = '{"country_code": "+91", "country_iso": "IN"}'::jsonb where setting_name = 'INDIA';
update master_settings set additional_info = '{"country_code": "+855", "country_iso": "KH"}'::jsonb where setting_name = 'CAMBODIA';
update master_settings set additional_info = '{"country_code": "+974", "country_iso": "QA"}'::jsonb where setting_name = 'QATAR';
