            select b.id::text as member_profile_id, b.name,                                                                                                                                                        
    jsonb_build_object(                                                                                                                                                                                            
        'name', b.name, 'birth_date', to_char(b.birth_date, 'dd FMMonth yyyy'), 'gender', b.gender,                                                                                                                
        'occupation', b.occupation, 'address', b.address, 'city_state', b.city ||' - '|| b.province                                                                                                                
        ||', '|| b.country, 'post_code', b.post_code, 'notes', b.notes                                                                                                                                             
    ) as profile, jsonb_build_object(                                                                                                                                                                              
        'join_expiry_date', to_char(c.join_date, 'dd FMMonth yyyy') ||' / '||                                                                                                                                      
        to_char(c.expiry_date, 'dd FMMonth yyyy'), 'dept_code', b.dept_code, 'dept_name', case when                                                                                                                
        f.channel_name ilike '%% || f.dept_name || %%' then f.channel_name else f.dept_name ||' - '||                                                                                                              
        f.channel_name end, 'group_id', d.id, 'group_name', d.group_name ||' - '|| d.group_tier,                                                                                                                   
        'rule_id', e.id, 'rule_name', e.rule_name,                                                                                                                                                                 
        'status', case when c.is_active is true then 'ACTIVE' else 'INACTIVE' end                                                                                                                                  
    ) as membership, jsonb_build_object('phone', a.phone, 'emails', b.emails) as contacts,                                                                                                                         
    b.additional_info                                                                                                                                                                                              
 from "public"."users" a                                                                                                                                                                                           
            inner join "public"."member_profiles" b on a.id = b.user_id                                                                                                                                            
            inner join "hgl"."member_registrations" c on b.id = c.member_profile_id                                                                                                                                
            inner join "hgl"."member_groups" d on c.member_group_id = d.id                                                                                                                                         
                inner join "hgl"."member_rules" e on c.member_rule_id = e.id                                                                                                                                       
                inner join "hgl"."departments" f on b.dept_code = f.dept_code                                                                                                                                      
                                                                                                                                                                                                                   
            where a.deleted_at is null and b.deleted_at is null and c.deleted_at is null                                                                                                                           
            and d.deleted_at is null and b.id = 'b5e6c9fd-40f2-4a11-80b5-a8a9a1e54afd' group by b.id, b.name,                                                                                                      
            b.gender, b.birth_date, b.address, b.city, b.province, b.country, b.post_code,                                                                                                                         
            b.notes, c.join_date, c.expiry_date, d.id, d.group_name, d.group_tier,                                                                                                                                 
            c.is_active, a.phone, b.emails                                                                                                                                                                         
                , e.id, case when f.channel_name ilike '%% || f.dept_name || %%'                                                                                                                                   
                then f.channel_name else f.dept_name ||' - '|| f.channel_name end
